# Generated by Django 5.0.7 on 2024-09-02 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "transaction_id",
                    models.CharField(
                        editable=False,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("transaction_details", models.TextField(max_length=120)),
                ("transaction_type", models.CharField(max_length=70)),
                ("transaction_date", models.DateField()),
                (
                    "transaction_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions_from",
                        to="myapp.accountnumber",
                    ),
                ),
                (
                    "transaction_to",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions_to",
                        to="myapp.accountnumber",
                    ),
                ),
            ],
        ),
    ]
