# Generated by Django 5.0.7 on 2024-09-04 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_alter_account_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="password",
            field=models.CharField(
                max_length=128,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)"
                    )
                ],
            ),
        ),
    ]
